# Generated by Django 2.2 on 2020-04-15 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20200415_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userposts', to='forum.UserPost'),
        ),
    ]
