# Generated by Django 2.2 on 2024-10-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0038_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='is_doctor',
            new_name='is_member',
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
