# Generated by Django 2.2 on 2025-01-25 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0042_auto_20250126_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='author',
        ),
    ]
